---
- hosts: prio
  become: True
  gather_facts: false
  name: Priority Systems
  tasks:
    - name: Copy anydesk on prio
      copy: src=/share/aquib.sayyed/anydesk-4.0.1-1.el6.x86_64.rpm dest=/srv/local mode=777

    - name: Installing Anydesk
      shell: rpm -ivh /srv/local/anydesk-4.0.1-1.el6.x86_64.rpm