---
- hosts: mariaserver
  become: True
  gather_facts: false
  name: Deploying MariaDB Server
  vars:
     mysql_root_password: root
  tasks:
    - name: Install MYSQL
      yum:
        name: mariadb-server #debian: mysql-server
        state: present
    - name: Install the Python MySQL Support Libraries
      yum: pkg=MySQL-python state=latest

    - name: start mysql server and enable it on reboot
      service: name=mariadb state=started enabled=true
    
    - name: update mysql root password for all root accounts
      mysql_user:
        name: root
        host: localhost
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
    - name: Move my.cnf file
      shell: mv /etc/my.cnf /etc/my.cnf_bkp

    - name: Copy the root credentials as .my.cnf file
      template: src=/etc/ansible/playbooks/maria/root.cnf.j2 dest=/etc/my.cnf mode=0600

    - name: Create a New Test DB called MyNewDB
      mysql_db: name=MyNewDB state=present login_user=root login_password={{ mysql_root_password }}