---
- hosts: smh
  gather_facts: True
  become: True
  vars_prompt:
    - name: "newlic_entry"
      prompt: "Enter Entry for newlic"
      private: no
  tasks:
    - name: check newlic in hosts
      shell: cat /etc/hosts | grep "newlic"
      register: newlic_status
      ignore_errors: True
    - debug:
        var: newlic_status

    - name: Add new in hosts
      shell: echo ' {{ newlic_entry }}'  >> /etc/hosts
      when: newlic_status.stdout == ""

    - name: change permission
      shell: chmod 777 /opt/Autodesk/ -R
    
    - name: stop service
      shell: /usr/bin/systemctl stop adsklicensing

    - name: remove .flexmrc
      shell: rm -rf /home/render/.flexlmrc

    - name: start service
      shell: /usr/bin/systemctl start adsklicensing

    - name: run newlic
      shell: /opt/Autodesk/AdskLicensing/9.2.1.2399/helper/AdskLicensingInstHelper change --prod_key 657L1 --prod_ver 2020.0.0.F --lic_servers 2080@newlic

    - name: check service status
      shell: /usr/bin/systemctl status adsklicensing