---
- hosts: system
  become: True
  become_user: jenkins
  gather_facts: true
  tasks: 

    - name: exec mate
      shell: sudo /ASE/app/00_workStationSetup/./systeminfo.sh
      register: check_out

    - debug:
        var: check_out.stdout_lines
