
---
- hosts: tera_lic
  become: yes
  name: Teradc License Check
  tasks:
    - name: Check License Expiration Date
      shell: pcoip-fne-view-license | tail -n 3 | head -n 1 | tr -s " " | cut -d " " -f 2,4,9
      register: lic
    - debug:
        var: lic.stdout