---
- hosts: ase
  become: True
  gather_facts: false
  name: Priority Systems
  tasks:
    - name: Replace 48 mount if present
      replace:
        path: /etc/fstab
        regexp: '192.168.1.48:/ifs/ASE 	/ASEP 	nfs 	defaults  	0 0'
        replace: '#192.168.1.48:/ifs/ASE 	/ASEP 	nfs 	defaults  	0 0'