---
- hosts: wazuh
  become: True
  gather_facts: true
  name: Install WAZUH client for ELK
  tasks:
    - name: Check Wazuh Client is installed
      shell: rpm -qa wazuh-agent-4.2.0-1.x86_64
      register: check_status
    - debug:
        var: check_status

    - name: Copy Wazuh Agent
      copy: src=/srv/local/wazuh-agent-4.2.0-1.x86_64.rpm dest=/srv/local mode=2777
      when: check_status.stdout == ""

    - name: Install Wazuh Agent
      shell: sudo WAZUH_MANAGER='192.168.1.155' WAZUH_AGENT_GROUP='default' rpm -ivh /srv/local/wazuh-agent-4.2.0-1.x86_64.rpm
      when: check_status.stdout == ""
      ignore_errors: True

    - name: Start Wazuh WAZUH_MANAGER
      service:
        name: wazuh-agent
        state: started
        enabled: yes