---
- hosts: vapt
  become: True
  gather_facts: True
  tasks:
    - name: Copy script
      copy: src=/etc/ansible/playbooks/vapt/vapt.sh dest=/var/tmp/ mode=2777

    - name: Install script for 6-10 vlan
      shell: /var/tmp/./vapt.sh
    
