---
- hosts: elk-server
  become: True
  gather_facts: True
  tasks:
    - name: install open-jdk
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - java-11-openjdk-devel 
        - java-11-openjdk
        